/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.edutec.appdemo.view;

import javax.swing.JOptionPane;
import javax.swing.plaf.RootPaneUI;
import pe.edutec.util.MyMath;

/**
 *
 * @author Alumno-CT
 */
public class PromedioView extends java.awt.Frame {

    /**
     * Creates new form PromedioView
     */
    public PromedioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtANum1 = new javax.swing.JTextField();
        txtANum2 = new javax.swing.JTextField();
        Procesar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtANum3 = new javax.swing.JTextField();
        txtANum4 = new javax.swing.JTextField();
        Procesar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtANum5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtANum6 = new javax.swing.JTextField();
        txtANum7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtANum8 = new javax.swing.JTextField();
        Procesar2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtANum9 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtANum10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Procesar3 = new javax.swing.JButton();
        txtANum11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtANum12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtANum13 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtANum14 = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel2.setText("Numero 1");
        jLabel2.setVerifyInputWhenFocusTarget(false);

        txtANum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANum2ActionPerformed(evt);
            }
        });

        Procesar.setLabel("Procesar");
        Procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcesarActionPerformed(evt);
            }
        });

        jLabel4.setText("Numero 2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtANum1)
                    .addComponent(txtANum2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Procesar, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtANum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtANum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(294, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("A-Prom.2", jPanel1);

        jLabel3.setText("Numero 1");
        jLabel3.setVerifyInputWhenFocusTarget(false);

        txtANum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANum4ActionPerformed(evt);
            }
        });

        Procesar1.setLabel("Procesar");
        Procesar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Procesar1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Numero 2");

        jLabel6.setText("Numero 3");

        txtANum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANum5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtANum5, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtANum3)
                            .addComponent(txtANum4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                .addGap(29, 29, 29)
                .addComponent(Procesar1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtANum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtANum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Procesar1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtANum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("B-Prom.3", jPanel2);

        jLabel7.setText("Numero 1");
        jLabel7.setVerifyInputWhenFocusTarget(false);

        txtANum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANum6ActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero 3");

        txtANum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANum8ActionPerformed(evt);
            }
        });

        Procesar2.setLabel("Procesar");
        Procesar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Procesar2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Numero 2");

        jLabel10.setText("Numero 4");

        txtANum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANum9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtANum9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtANum7)
                            .addComponent(txtANum6)
                            .addComponent(txtANum8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addComponent(Procesar2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtANum7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtANum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtANum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtANum9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Procesar2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(219, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("C-Prom.4", jPanel3);

        txtANum10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANum10ActionPerformed(evt);
            }
        });

        jLabel11.setText("Numero 2");

        jLabel12.setText("Numero 4");

        Procesar3.setLabel("Procesar");
        Procesar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Procesar3ActionPerformed(evt);
            }
        });

        txtANum11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANum11ActionPerformed(evt);
            }
        });

        jLabel13.setText("Numero 3");

        jLabel14.setText("Numero 1");
        jLabel14.setVerifyInputWhenFocusTarget(false);

        txtANum13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANum13ActionPerformed(evt);
            }
        });

        jLabel15.setText("Numero 5");

        txtANum14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANum14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtANum14))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(txtANum10))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel11)
                                .addComponent(jLabel13))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtANum12)
                                .addComponent(txtANum13)
                                .addComponent(txtANum11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(53, 53, 53)
                .addComponent(Procesar3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtANum12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtANum13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtANum11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtANum10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Procesar3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtANum14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jLabel15.getAccessibleContext().setAccessibleName("Numero 5");

        jTabbedPane1.addTab("D-Prom.5", jPanel4);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        jTabbedPane1.getAccessibleContext().setAccessibleName("D-Prom.5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void txtANum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANum2ActionPerformed

    private void ProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesarActionPerformed
        // TODO add your handling code here:
        //Variables
        int n1, n2, prom;
        String repo;
        //Datos
        n1 = Integer.parseInt(txtANum1.getText());
        n2 = Integer.parseInt(txtANum2.getText());
        //Proceso
        MyMath obj= new MyMath();
        prom = obj.promedio(n1, n2);
        //Reporte
        repo = "Promedio: "+ prom;
        JOptionPane.showMessageDialog(rootPane, repo);
    }//GEN-LAST:event_ProcesarActionPerformed

    private void txtANum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANum4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANum4ActionPerformed

    private void Procesar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Procesar1ActionPerformed
        // TODO add your handling code here:
        int n1, n2, n3, prom;
        String repo;
        //Datos
        n1 = Integer.parseInt(txtANum3.getText());
        n2 = Integer.parseInt(txtANum4.getText());
        n3 = Integer.parseInt(txtANum5.getText());
        //Proceso
        MyMath obj= new MyMath();
        prom = obj.promedio(n1, n2, n3);
        //Reporte
        repo = "Promedio: "+ prom;
        JOptionPane.showMessageDialog(rootPane, repo);
    }//GEN-LAST:event_Procesar1ActionPerformed

    private void txtANum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANum5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANum5ActionPerformed

    private void txtANum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANum6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANum6ActionPerformed

    private void txtANum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANum8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANum8ActionPerformed

    private void Procesar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Procesar2ActionPerformed
        // TODO add your handling code here:
        int n1, n2, n3, n4, prom;
        String repo;
        //Datos
        n1 = Integer.parseInt(txtANum6.getText());
        n2 = Integer.parseInt(txtANum7.getText());
        n3 = Integer.parseInt(txtANum8.getText());
        n4 = Integer.parseInt(txtANum9.getText());
        //Proceso
        MyMath obj= new MyMath();
        prom = obj.promedio(n1, n2, n3, n4);
        //Reporte
        repo = "Promedio: "+ prom;
        JOptionPane.showMessageDialog(rootPane, repo);
    }//GEN-LAST:event_Procesar2ActionPerformed

    private void txtANum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANum9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANum9ActionPerformed

    private void txtANum10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANum10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANum10ActionPerformed

    private void Procesar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Procesar3ActionPerformed
        // TODO add your handling code here:
           int n1, n2, n3, n4, n5, prom;
        String repo;
        //Datos
        n1 = Integer.parseInt(txtANum6.getText());
        n2 = Integer.parseInt(txtANum7.getText());
        n3 = Integer.parseInt(txtANum8.getText());
        n4 = Integer.parseInt(txtANum9.getText());
        n5 = Integer.parseInt(txtANum9.getText());
        //Proceso
        MyMath obj= new MyMath();
        prom = obj.promedio(n1, n2, n3, n4, n5);
        //Reporte
        repo = "Promedio: "+ prom;
        JOptionPane.showMessageDialog(rootPane, repo);
        
    }//GEN-LAST:event_Procesar3ActionPerformed

    private void txtANum11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANum11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANum11ActionPerformed

    private void txtANum13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANum13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANum13ActionPerformed

    private void txtANum14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANum14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANum14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PromedioView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Procesar;
    private javax.swing.JButton Procesar1;
    private javax.swing.JButton Procesar2;
    private javax.swing.JButton Procesar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtANum1;
    private javax.swing.JTextField txtANum10;
    private javax.swing.JTextField txtANum11;
    private javax.swing.JTextField txtANum12;
    private javax.swing.JTextField txtANum13;
    private javax.swing.JTextField txtANum14;
    private javax.swing.JTextField txtANum2;
    private javax.swing.JTextField txtANum3;
    private javax.swing.JTextField txtANum4;
    private javax.swing.JTextField txtANum5;
    private javax.swing.JTextField txtANum6;
    private javax.swing.JTextField txtANum7;
    private javax.swing.JTextField txtANum8;
    private javax.swing.JTextField txtANum9;
    // End of variables declaration//GEN-END:variables
}
