/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.angeles.view;

import pe.angeles.util.MyMath;

/**
 *
 * @author Alumno-CT
 */
public class FactorialView extends javax.swing.JInternalFrame {

    /**
     * Creates new form FactorialView
     */
    private static FactorialView instancia = null;  

    public static FactorialView getInstancia(){  

        if( instancia == null ){  
            instancia = new FactorialView();  
        }  
        return instancia;  

    }    
    
    private FactorialView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxareaFactorial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCalcularFactorial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxareaFactorialResultado = new javax.swing.JTextArea();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FACTORIAL");

        jLabel1.setText("Ingrese el número");

        btnCalcularFactorial.setText("Calcular");
        btnCalcularFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularFactorialActionPerformed(evt);
            }
        });

        jtxareaFactorialResultado.setColumns(20);
        jtxareaFactorialResultado.setRows(5);
        jScrollPane1.setViewportView(jtxareaFactorialResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCalcularFactorial)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(64, 64, 64)
                            .addComponent(jtxareaFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxareaFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addComponent(btnCalcularFactorial)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularFactorialActionPerformed
        // TODO add your handling code here:
        long resultado;
        resultado=MyMath.factorial(Integer.parseInt(jtxareaFactorial.getText()));
        jtxareaFactorialResultado.setText("");
        jtxareaFactorialResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnCalcularFactorialActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularFactorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxareaFactorial;
    private javax.swing.JTextArea jtxareaFactorialResultado;
    // End of variables declaration//GEN-END:variables
}
